version: 0.1

environment_variables:
  plaintext:
    Variables: "go here"

phases:
  install:
    commands:
      - echo Install numpy dependencies...
      - pip install --upgrade pip
      - pip install numpy --target=./
  pre_build:
    commands:
      - echo Pre Build...
      - ls
  build:
    commands:
      - echo Start build...
  post_build:
    commands:
      - echo Build completed...
      - ls

artifacts:
  files:
    - lambda.py
    - requirements.txt
    - numpy/**/*
    - numpy-*/**/*