version: 0.1

environment_variables:
  plaintext:
    Variables: "go here"

phases:
  install:
    commands:
      - mkdir lambda
      - echo Install numpy dependencies...
      - pip install --upgrade pip
      - pip install numpy --target=./lambda
  pre_build:
    commands:
      - echo Pre Build...
      - mv lambda.py ./lambda
  build:
    commands:
      - echo Start build...
      - zip -r lambda.zip ./lambda
  post_build:
    commands:
      - echo Build completed...
      - ls

artifacts:
  files:
    - lambda.zip
    - swagger-2.yml
    - deploy.yml