version: 0.1

environment_variables:
  plaintext:
    Variables: "go here"

phases:
  install:
    commands:
      - echo Install numpy dependencies...
      - pip install numpy --target=./
  pre_build:
    commands:
      - echo Pre Build...
  build:
    commands:
      - echo Start build...
  post_build:
    commands:
      - echo Build completed...
      
artifacts:
  type: zip
  files:
    - lambda.py
    - requirements.txt
    - numpy/
    - numpy-*/