version: 0.1

environment_variables:
  plaintext:
    Variables: "go here"

phases:
  install:
    commands:
      - echo Install numpy dependencies...
  pre_build:
    commands:
      - echo Nothing to do...
  build:
    commands:
      - echo Start build...
      - zip -r built_api *
  post_build:
    commands:
      - echo Build completed...
artifacts:
  files:
    - built_api.zip