version: 0.1

environment_variables:
  plaintext:
    Variables: "go here"

phases:
  install:
    commands:
      - mkdir lambda
      - pip install --upgrade pip
      - pip install numpy --target=./
  pre_build:
    commands:
      - yum install zip -y
  build:
    commands:
      - zip -r lambda.zip lambda.py numpy*/
      - zipinfo lambda.zip
  post_build:
    commands:
      - aws cloudformation package --template deploy.yml --output-template-file serverless-deploy.yml --s3-bucket mda-cloudformation

artifacts:
  files:
    - lambda.zip
    - swagger-2.yml
    - serverless-deploy.yml