AWSTemplateFormatVersion: '2010-09-09'
Description: An AWS Serverless Specification template describing your function.
Resources:
  CloudPingApiFunction:
    Properties:
      CodeUri: s3://mda-cloudformation/7313a5a987888ed400b27fd81cec5d52
      Description: ''
      Events:
        AveragesApi:
          Properties:
            Method: GET
            Path: /averages
            RestApiId:
              Ref: CloudPingApiGateway
          Type: Api
        AveragesDayApi:
          Properties:
            Method: GET
            Path: /averages/day
            RestApiId:
              Ref: CloudPingApiGateway
          Type: Api
        AveragesDayNumApi:
          Properties:
            Method: GET
            Path: /averages/day/{numdays}
            RestApiId:
              Ref: CloudPingApiGateway
          Type: Api
        AveragesMonthApi:
          Properties:
            Method: GET
            Path: /averages/month
            RestApiId:
              Ref: CloudPingApiGateway
          Type: Api
        AveragesMonthNumApi:
          Properties:
            Method: GET
            Path: /averages/month/{nummonths}
            RestApiId:
              Ref: CloudPingApiGateway
          Type: Api
        AveragesQueryApi:
          Properties:
            Method: POST
            Path: /query
            RestApiId:
              Ref: CloudPingApiGateway
          Type: Api
        AveragesWeekApi:
          Properties:
            Method: GET
            Path: /averages/week
            RestApiId:
              Ref: CloudPingApiGateway
          Type: Api
        AveragesWeekNumApi:
          Properties:
            Method: GET
            Path: /averages/week/{numweeks}
            RestApiId:
              Ref: CloudPingApiGateway
          Type: Api
      Handler: lambda.lambda_handler
      MemorySize: 256
      Role: arn:aws:iam::506666621600:role/lambda_basic_execution
      Runtime: python2.7
      Timeout: 30
    Type: AWS::Serverless::Function
  CloudPingApiGateway:
    Properties:
      DefinitionUri: s3://mda-cloudformation/25a7ff7c4a0698302614bdb9412d023d
      StageName: v1
      Variables:
        LambdaAcctId:
          Ref: AWS::AccountId
        LambdaFunctionName:
          Ref: CloudPingApiFunction
        LambdaRegion:
          Ref: AWS::Region
    Type: AWS::Serverless::Api
Transform: AWS::Serverless-2016-10-31
